version: '3.3'
services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        container_name: php73
        depends_on:
            - db
        volumes:
            - ./web:/var/www/html/
        ports:
            - 80:80
    db:
        container_name: mysql8
        image: mysql:8.0
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: discordv1.1
            MYSQL_USER: devMasaryk
            MYSQL_PASSWORD: devMUNI
        volumes:
            - ./sql-scripts:/docker-entrypoint-initdb.d
        ports:
            - 6033:3306
    phpmyadmin:
        container_name: phpmyadmin48
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - 81:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - db
    python:
        container_name: python37
        build:
            context: ./bot
            dockerfile: Dockerfile
        depends_on:
            - db
