version: '3.7'

services:
  snekbox:
    container_name: snekbox
    image: pythondiscord/snekbox:latest
    init: true
    ipc: none
    ports:
     - "127.0.0.1:8060:8060"
    privileged: true

  bot:
    container_name: bot
    build: bot/
    volumes:
      - .:/MasarykBOT
    env_file: .env
    depends_on:
      - snekbox
