version: '3.6'

services:
    bot:
        build: .
        env_file: .env
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        command: python __main__.py
        #restart: unless-stopped