version: '3.8'

services:
  snekbox:
    container_name: snekbox
    build:
      context: .
      dockerfile: snekbox/Dockerfile.snekbox

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile.bot
    volumes:
      - .:/MasarykBOT
    env_file: .env
    network_mode: host
    depends_on:
      - snekbox
