version: '3.8'

services:
  snekbox:
    container_name: snekbox
    image: pythondiscord/snekbox:latest
    init: true
    ipc: none
    ports:
     - "8060:8060"
    privileged: true

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile.bot
    volumes:
      - .:/MasarykBOT
    env_file: .env
    network_mode: host
    depends_on:
      - snekbox
