name: Deploy

on:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.2.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "masarykbot-v2" #Must be unique in Heroku
          heroku_email: "zloutek1@gmail.com"
          procfile: "worker: python __main__"
          usedocker: true
